[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SZ plugin guide"
authors = [{name = "Giacomo Titti", email = "giacomotitti@gmail.com"}]
dynamic = ["version", "description"]
